### ISSUE TITLE
Customer ID gets overwritten with wrong values

### ISSUE THREAD

**Issue by drazenbebic** [drazenbebic/license-manager-for-woocommerce#103]
**Describe the bug**
When completing orders that don't have license keys yet via the Dashboard, instead of the customer user ID, the plugin writes the currently logged in user ID (the admin) for the sold/generate license keys.

**Comment by drazenbebic** [comment]
Fixed in #104

**Comment by AdrianMarikar** [comment]
@drazenbebic 

I am still having this issue in version 2.2.0 .

Just to make sure it is same issue I'll write my steps.

Woocommerce set up with Cash on Delivery for testing.

User buys license key from front-end woocommerce store. 

Admin goes in to back-end Orders in WooCommerce. Order status is set to Holding. 

Admin changes to Completed.

When Admin goes in to check License Manager, the customer for the sold license is the Admin.
